### ISSUE TITLE
kernel 4.4.50-v7+ cannot be found

### ISSUE THREAD

**Issue by loskiq** [lord2y/rtl8192eu-arm-linux-driver#1]
`root@raspberrypi:~/rtl8192eu-arm-linux-driver-master# dkms install rtl8192eu/1.0`
`Error! echo`
`Your kernel headers for kernel 4.4.50-v7+ cannot be found at`
`/lib/modules/4.4.50-v7+/build or /lib/modules/4.4.50-v7+/source.`

What is this?

**Comment by lord2y** [comment]
did you install this package ``raspberrypi-kernel-headers``?

**Comment by elysiandc** [comment]
Seems I'm getting the same thing...
```
~/rtl8192eu-arm-linux-driver# dkms install rtl8192eu/1.0
Error! echo
Your kernel headers for kernel 4.9.27-v7+ cannot be found at
/lib/modules/4.9.27-v7+/build or /lib/modules/4.9.27-v7+/source.

```
I have double checked that and `raspberrypi-kernel-headers` are installed and showing as the latest version.

**Comment by lord2y** [comment]
I tried to reproduce your issue but without success.
Here my environment:

    # lsb_release -a
    No LSB modules are available.
    Distributor ID:	Raspbian
    Description:	Raspbian GNU/Linux 8.0 (jessie)
    Release:	8.0
    Codename:	jessie
 
    # uname -r
    4.9.24+
    # dpkg-query -l | grep raspberrypi-kernel-headers
    ii  raspberrypi-kernel-headers     1.20170427-1     armhf    Header files for the Raspberry Pi Linux kernel

    tree -L 1 -d /lib/modules/`uname -r`
    /lib/modules/4.9.24+
    ├── build -> /usr/src/linux-headers-4.9.24+
    └── kernel`



This was a fresh installation with the last image available [here](https://www.raspberrypi.org/downloads/raspbian/).

I did an upgrade before start, then I followed the instruction in the README.

    # apt-get install git raspberrypi-kernel-headers build-essential dkms

Then I cloned the repo and followed the remaining steps: 

  ``` 
   # git clone https://github.com/lord2y/rtl8192eu-arm-linux-driver.git
   # cd rtl8192eu-arm-linux-driver
   # dkms add .
   Creating symlink /var/lib/dkms/rtl8192eu/1.0/source ->
                 /usr/src/rtl8192eu-1.0

   DKMS: add completed.
   # dkms install rtl8192eu/1.0 
   Kernel preparation unnecessary for this kernel.  Skipping...
 
   Building module:
   cleaning build area....
   'make' 
  
 ARCH=arm.................................................................................................................................................................................................................................................
   cleaning build area....

   DKMS: build completed.

   8192eu.ko:
   Running module version sanity check.
    - Original module
    - No original module exists within this kernel
    - Installation
    - Installing to /lib/modules/4.9.24+/kernel/drivers/net/wireless//

   depmod.....

   : Unable to find an initial ram disk that I know how to handle.
   Will not try to make an initrd.

DKMS: install completed.
```
It worked.

I cannot reproduce.
