### ISSUE TITLE
new raspberry kernel 4.14.30-v7+ #1102 for RaspberryPI B+ won't build

### ISSUE THREAD

**Issue by thecalle** [lord2y/rtl8192eu-arm-linux-driver#2]
make errors:

make ARCH=arm CROSS_COMPILE= -C /lib/modules/4.14.30-v7+/build M=/usr/src/rtl8192eu-arm-linux-driver  modules
make[1]: Entering directory '/usr/src/linux-headers-4.14.30-v7+'
  CC [M]  /usr/src/rtl8192eu-arm-linux-driver/core/rtw_cmd.o
In file included from /usr/src/rtl8192eu-arm-linux-driver/include/drv_types.h:32:0,
                 from /usr/src/rtl8192eu-arm-linux-driver/core/rtw_cmd.c:22:
/usr/src/rtl8192eu-arm-linux-driver/include/osdep_service.h: In function ‘thread_enter’:
/usr/src/rtl8192eu-arm-linux-driver/include/osdep_service.h:342:2: error: implicit declaration of function ‘allow_signal’ [-Werror=implicit-function-declaration]
  allow_signal(SIGTERM);
  ^~~~~~~~~~~~
/usr/src/rtl8192eu-arm-linux-driver/include/osdep_service.h: In function ‘flush_signals_thread’:
/usr/src/rtl8192eu-arm-linux-driver/include/osdep_service.h:352:6: error: implicit declaration of function ‘signal_pending’ [-Werror=implicit-function-declaration]
  if (signal_pending (current))
      ^~~~~~~~~~~~~~
/usr/src/rtl8192eu-arm-linux-driver/include/osdep_service.h:354:3: error: implicit declaration of function ‘flush_signals’ [-Werror=implicit-function-declaration]
   flush_signals(current);
   ^~~~~~~~~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:328: recipe for target '/usr/src/rtl8192eu-arm-linux-driver/core/rtw_cmd.o' failed
make[2]: *** [/usr/src/rtl8192eu-arm-linux-driver/core/rtw_cmd.o] Error 1
Makefile:1519: recipe for target '_module_/usr/src/rtl8192eu-arm-linux-driver' failed
make[1]: *** [_module_/usr/src/rtl8192eu-arm-linux-driver] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.14.30-v7+'
Makefile:1335: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by lord2y** [comment]
I was able to reproduce your issue.
I made several changes to this repo, could you please try with code in branch [fix-for-4.14.34](https://github.com/lord2y/rtl8192eu-arm-linux-driver/tree/fix-for-4.14.34)?

Works for me on 

    Description:	Raspbian GNU/Linux 9.4 (stretch)
    Release:	9.4
    Codename:	 stretch

With kernel

    Linux raspberrypi 4.14.34+ #1110 Mon Apr 16 14:51:42 BST 2018 armv6l GNU/Linux

**Comment by ghost** [comment]
make ARCH=arm CROSS_COMPILE= -C /lib/modules/4.14.30-v7+/build M=/home/#######/Downloads/rtl8192eu-arm-linux-driver-fix-for-4.14.34  modules
make[1]: *** /lib/modules/4.14.30-v7+/build: No such file or directory.  Stop.
Makefile:1700: recipe for target 'modules' failed
make: *** [modules] Error 2

Duno if error is in my setup, or am i missing something... But i tried your fix branch and got this error...

**Comment by lord2y** [comment]
@Mafields it seems you don't have the headers installed.

Did you run this command first:

    $ sudo apt-get install git raspberrypi-kernel-headers build-essential dkms

If not please do, clean up the env with

    $ make clean

and try to compile the driver again.

**Comment by Equinox86** [comment]
Note: when running  you will need to go into the Makefile and change the platform per https://github.com/diederikdehaas/rtl8812AU/issues/34
