### ISSUE TITLE
Drivers for Android

### ISSUE THREAD

**Issue by leoatinnovation** [lord2y/rtl8192eu-arm-linux-driver#9]
Hi , 

I have installed the drivers for Raspberry Pi 3 running Raspbian and its work fine. Thanks to you. 

I have flashed Android on Rp3 and trying to use DWA -131. Do we have drivers for that . If so could you post the link?

**Comment by lord2y** [comment]
> Hi ,
> 
> I have installed the drivers for Raspberry Pi 3 running Raspbian and its work fine. Thanks to you.

Glad to hear that. You're welcome 😄 
> 
> I have flashed Android on Rp3 and trying to use DWA -131. Do we have drivers for that . If so could you post the link?

I think you could give a try to this driver using arm as arch. Not sure though whether Android's kernels need 
something special.
If you'll try you could drop me an email with the outcome.
